spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/product-manager
    username: product-admin
    password: Admin123
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop
